#!/usr/bin/env ruby
# frozen_string_literal: true

#
# frequency-list
#
# Input:  A list of lines.
# Output: The unique lines in the input, sorted by frequency of occurrence.
#
# EXAMPLE
#
# Input:
#
#   apple
#   banana
#   apple
#   cherry
#
# Output:
#
#   2 apple
#   1 banana
#   1 cherry
#

lines = ARGF.readlines

frequency = lines.each_with_object(Hash.new(0)) do |line, counts|
  counts[line.chomp] += 1
end

sorted_frequency = frequency.sort_by { |_, count| -count }

sorted_frequency.each do |line, count|
  puts "#{count} #{line}"
end
